management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${KEYCLOAK_HOST:localhost}:8080/realms/countries-and-cities-main-realm
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 31150616
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/city
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.yaml

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

springdoc:
  api-docs:
    enabled: true
jwt:
  auth:
    converter:
      resource-id: cities-and-countries
      principal-attribute: preferred_username
minio:
  username: minio-root-user
  password: minio-root-password
  url: http://${MINIO_HOST:localhost}:9000
  bucket-name: logo-storage

server:
  port: 8088
