name: CI Andresen Cities and Countries

on:
  push:
    branches: [ "main" ]
    
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name : Step 1 - Checkout main branch from VSC 
      uses: actions/checkout@v3
      
    - name: Step 2 - Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml

    - name : Step 4 - Check target folder
      run : |
        cd target
        ls -a
